name: Smoke test
on:
  workflow_call:

jobs:
  test_docker_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Build, no push
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker compose for last commit
        env:
          TAG: ${{ github.ref_name }}
          REPO_NAME: ${{ github.event.repository.name }}
        working-directory: docker/
        run: |
          docker compose -f compose.e2e.yml up --pull=never --wait-timeout=60 --wait
          echo "Echo docker ps -a:"
          docker ps -a
          echo "Echo logs:"
          docker compose logs
          docker compose down
