name: Smoke test
on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      tag_name:
        required: false
        type: string
        default: ci_test

jobs:
  test_docker_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Build, no push
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: false
          tags: ghcr.io/taranis-ai/${{ inputs.repo_name }}:${{ inputs.tag_name }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker compose for last commit
        env:
          REPO_NAME: ${{ inputs.repo_name }}
          TAG: ${{ inputs.tag_name }}
        working-directory: docker/
        run: |
          docker compose -f compose.e2e.yml up --pull=never --wait-timeout=60 --wait
          echo "Echo docker ps -a:"
          docker ps -a
          echo "Echo logs:"
          docker compose -f compose.e2e.yml logs
          docker compose -f compose.e2e.yml down
